@startuml
/'la autora es imane Alouane'/
class C_Usuario<<Entity>>{ 

nombre 

fecha:Date

estatura:Integer  

peso:Integer 

genero:E_Genero 

email:String  

pasword:String 
estaActivo:BOOLEAN
fechaAlta:Date 

fechaBaja:Date [0..1] 

colorPelo:E_ColorPelo 

colorOjo: E_ColorOjos 

} 


Class C_Foto<<Entity>>{ 

Url:String 

nombre:string 

Descripción:string 
fecha:date

} 
note as RN_usuarios
<b> RN-1-0a </b> Todos los datos excepto la feha de baja son obligatorios. 
Una fecha de baja nula repersentaa un usuario activo y
 viceversa un usuario que se ha dado de baja logicamente.
 <b> RN-1-0b </b> El peso(kg) y la altura(cm) son positivos
 <b> RN-1-0z </b> Los valores por defectoson 75 kg de peso, 170 cm de altura y el color de pelo es negro.
 <b> RN-1-1 </b>En el momento de alta todos los usuarios registrados deben de ser mayores de 18 años.
 <b> RN-1-2 </b> El email sirve como identificador y por tanto ha de de ser unico
 <b> RN-1-3 </b> La fecha de alta ha de ser posterior a las de nacimiento, 
 y de existir la fecha de baja debe de ser posterior a la de alta.

 end note

note as RN_fotos 
<b> RN-1-0c </b> Es obligatorio que las fotos tengan nombre descripcion y url.
<b> RN-1-4 </b> Solo se pueden almacenar un máximo de 5 fotos por usuario
end note 

RN_usuarios-- C_Usuario
RN_fotos -- C_Foto


C_Usuario"1"-up-"[0..5]"C_Foto:> Sube 

@enduml
