@startuml
/'la autora es imane Alouane'/
 
class C_Conversacion<<Entity>>{ 
/'
se deducen de la asociacion , así que no hace falta ponerlos 
Participante1:C_Usuario 

Participante2:C_Usuario 
'/

fecha_inicio: Date 
fecha_fin: Date [0..1] 
/new_mensaje:boolean 

} 

class C_Mensaje<<Entity>>{ 

Instante:datetime
/'
igualr que con conversaciones, creo que no hacen falta
emisor:C_Usuario
receptor:C_Usuario
'/
Texto:String 

     

} 

note as RN_conversaciones
<b> RN-4-00 </b> Todos los datos de una conversacion y de un mensaje son obligatorios.
<b> RN-4-01 </b> La conversación termine (fecha de finalización) despues del inicio(fecha de inicio).
<b> RN-4-02 </b> Una conversacío solo puede crearse bajo un vínculo de amistad actvo, En caso contrario ni se muestra la opción  ni podrá definirse en el sistema.
end note

note as RN_mensajes
<b> RN-4-0 </b> todos los datos de una conversadcion de un mensaje son obligatorios.
<b> RN-4-3 </b> el instante en el que se genera ubn mensaje esté dntro del intervalo definido para una Conversación( que está activa si no tiene fecha de fin).
Ningun mensaje puede ser posterior al cierra de una conversacion.
end note

RN_conversaciones --C_Conversacion
RN_mensajes -- C_Mensaje

C_Conversacion*--"*"C_Mensaje:compuesta
@enduml 
